export enum Feedback {
  DECREASED = 'DECREASED',
  INCREASED = 'INCREASED',
  HIGHLY_INCREASED = 'HIGHLY_INCREASED',
  NO_CHANGE_NO_ADJUSTMENTS = 'NO_CHANGE_NO_ADJUSTMENTS',
  NO_CHANGE_BALANCED = 'NO_CHANGE_BALANCED',
}
