export enum SleepHistoryAdjustment {
  DECREASING = 'DECREASING',
  DECREASING_HIGH_QUALITY = 'DECREASING_HIGH_QUALITY',
  INCREASING_LOW_QUALITY = 'INCREASING_LOW_QUALITY',
  INCREASING = 'INCREASING',
  NO_CHANGE = 'NO_CHANGE',
  NO_DATA = 'NO_DATA',
}
