export enum SleepScoreInsight {
  NONE = 'NONE',
  POSITIVE_LATE_BED_TIME = 'POSITIVE_LATE_BED_TIME',
  POSITIVE_RESTFUL_EVENING = 'POSITIVE_RESTFUL_EVENING',
  POSITIVE_STRESSFUL_DAY = 'POSITIVE_STRESSFUL_DAY',
  POSITIVE_EXERCISE = 'POSITIVE_EXERCISE',
  POSITIVE_RESTFUL_DAY = 'POSITIVE_RESTFUL_DAY',
  NEGATIVE_LATE_BED_TIME = 'NEGATIVE_LATE_BED_TIME',
  NEGATIVE_HIGHLY_STRESSFUL_DAY = 'NEGATIVE_HIGHLY_STRESSFUL_DAY',
  NEGATIVE_STRESSFUL_DAY = 'NEGATIVE_STRESSFUL_DAY',
  NEGATIVE_LATE_STRENUOUS_EXERCISE = 'NEGATIVE_LATE_STRENUOUS_EXERCISE',
  NEGATIVE_LATE_EXERCISE = 'NEGATIVE_LATE_EXERCISE',
  NEGATIVE_STRENUOUS_EXERCISE = 'NEGATIVE_STRENUOUS_EXERCISE',
}
