export enum TrainingFeedback {
  NO_CHANGE = 'NO_CHANGE',
  DAILY_ACTIVITY = 'DAILY_ACTIVITY',
  DAILY_ACTIVITY_AND_CHRONIC = 'DAILY_ACTIVITY_AND_CHRONIC',
  HIGH_ACWR = 'HIGH_ACWR',
  TODAYS_LOAD = 'TODAYS_LOAD',
}
